#include<iostream>
using namespace std;
int main()
{
    int m,bai,wu,er,shi,yi,five;
    cin>>m;
    if(m>=100)
    {
        bai=m/100;
        m=m-bai*100;
        if(m>=50)
        {
            wu=m/50;
            m=m-wu*50;
            if(m>=20)
            {
                er=m/20;
                m=m-er*20;
                if(m>=10)
                {
                    shi=m/10;
                    m=m-shi*10;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
                else
                {
                    shi=0;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
            }
            else
            {
                er=0;
                if(m>=10)
                {
                    shi=m/10;
                    m=m-shi*10;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
                else
                {
                    shi=0;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
            }
        }
        else
        {
            wu=0;
            if(m>=20)
            {
                er=m/20;
                m=m-er*20;
                if(m>=10)
                {
                    shi=m/10;
                    m=m-shi*10;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
                else
                {
                    shi=0;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
            }
            else
            {
                er=0;
                if(m>=10)
                {
                    shi=m/10;
                    m=m-shi*10;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
                else
                {
                    shi=0;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
            }
        }
    }
    else
    {
        bai=0;
        if(m>=50)
        {
            wu=m/50;
            m=m-wu*50;
            if(m>=20)
            {
                er=m/20;
                m=m-er*20;
                if(m>=10)
                {
                    shi=m/10;
                    m=m-shi*10;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
                else
                {
                    shi=0;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
            }
            else
            {
                er=0;
                if(m>=10)
                {
                    shi=m/10;
                    m=m-shi*10;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
                else
                {
                    shi=0;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
            }
        }
        else
        {
            wu=0;
            if(m>=20)
            {
                er=m/20;
                m=m-er*20;
                if(m>=10)
                {
                    shi=m/10;
                    m=m-shi*10;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
                else
                {
                    shi=0;
                   if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
            }                
            else
            {
                er=0;
                if(m>=10)
                {
                    shi=m/10;
                    m=m-shi*10;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
                else
                {
                    shi=0;
                    if(m>=5)
                    {
                        five=m/5;
                        m=m-five*5;                    
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                    else
                    {
                        five=0;
                        if(m>=1)
                        {
                            yi=m;
                        }
                        else
                        {
                            yi=0;
                        }
                    }
                }
            }
        }
    }
    cout<<bai<<endl;
    cout<<wu<<endl;
    cout<<er<<endl;
    cout<<shi<<endl;
    cout<<five<<endl;
    cout<<yi<<endl;
    return 0;
}
            

            
                
                
